# ひとことメモ

## Start 関数で終了処理をするな

たとえばサーバーのプログラムで Start で立ち上げて、それが終われば終了のようなプログラムを作るな

```Go
func Start() error {
    hoge.Start()
    defer hoge.Close()
    fuga.Start()
    defer huga.Close()

    <- StopChannel
    return nil
}
```

このエラーは何を意味する？  
Start でエラーが出た場合も、終了処理で出たエラーもすべて Start のエラーになってしまう。

正しくは

```Go
func main(){
    err ;= Start()
    if err != nil {
        // エラー処理
    }
    <- stopChannel

    err = Finalize()
    return 0
}

type App struct {
    hoge Hoge
    fuga Fuga
}

func (app App) Start() error{
    err ;= hoge.Start()
    if err != nil {
        return err
    }

    err = fuga.Start()
    if err != nil {
        return
    }
    return nil
}

func (app App) Finalize() error {
    var retErr error
    err := hoge.Close()
    if err != nil {
        retErr = errors.Wrap(retErr, err.Error())
    }
    err := fuga.Close()
    if err != nil {
        retErr = errors.Wrap(retErr, err.Error(())
    }
    return retError
}
```
