# ひとことメモ

## Start 関数で終了処理をするな

たとえばサーバーのプログラムで Start で立ち上げて、それが終われば終了のようなプログラムを作るな

```Go
func Start() error {
    hoge.Start()
    defer hoge.Close()
    fuga.Start()
    defer huga.Close()

    <- StopChannel
    return nil
}
```

このエラーは何を意味する？  
Start でエラーが出た場合も、終了処理で出たエラーもすべて Start のエラーになってしまう。

正しくは

```Go
func main(){
    err ;= Start()
    if err != nil {
        // エラー処理
    }
    <- stopChannel

    err = Finalize()
    return 0
}

type App struct {
    hoge Hoge
    fuga Fuga
}

func (app App) Start() error{
    err ;= hoge.Start()
    if err != nil {
        return err
    }

    err = fuga.Start()
    if err != nil {
        return
    }
    return nil
}

func (app App) Finalize() error {
    var retErr error
    err := hoge.Close()
    if err != nil {
        retErr = errors.Wrap(retErr, err.Error())
    }
    err := fuga.Close()
    if err != nil {
        retErr = errors.Wrap(retErr, err.Error(())
    }
    return retError
}
```

## Logger はエラーハンドリングもしろ

AWS 上でサーバーが勝手にスケール・イン/アウトする環境でログの欠損が発生した。  
課金ログだったため、欠損率０を目指すべく調査を開始。

まず、AWS サポートに当たってみたところ、Fargate のスケール・イン/アウトは Graceful Shutdown の思想が取り入れられていた。

1. `SIGTERM`を送信して終了させる。
2. `SIGTERM`で死ななかった場合、`SIGKILL`を送信して強制終了する。

そのため、`SIGTERM`受信時にメモリフラッシュを行って、バッファリングしてるログをすべてファイルに書き出す処理が必要となった。

実装は特にむずかしく「`SIGTERM`を受けたら〇〇する」でなく、デストラクション時にフラッシュする処理を導入した。

## テストとは

テストは品質を上げるものではない  
テストは品質を知るためのもの  
品質を上げるのは継続的なリファクタリング  
